# Lastkajen
# Telia OD csv
# Real Network

"""
    Carga datos de tráfico desde un archivo pickle y construye un objeto Data de PyTorch Geometric.

    El archivo pickle debe contener un diccionario con claves 'nodes' y 'links' que incluyen:
      - nodes: 'node.ids', 'node.type', 'node.coordinates', 'node.demand'
      - links: 'link.ids', 'link.type', 'link.ij', 'link.observed_flow'

    Se buscan el archivo en múltiples rutas si es necesario.

    Args:
        pickle_name (str): Ruta relativa del archivo pickle (p.ej., "data/traffic_data_10.pkl").

    Returns:
        Data: Objeto PyTorch Geometric con atributos:
            - x: tensor de características [num_nodes, 4] (ej. [is_zat, is_intersection, gen, attr]).
            - edge_index: tensor de aristas [2, num_edges].
            - observed_flow_indices, observed_flow_values: tensores para flujos observados.
            - node_coordinates: lista de coordenadas para visualización.
            - node_types: lista de tipos de nodo.
            - zat_demands: diccionario con demandas de nodos ZAT.
            - node_id_map_rev: mapeo índice -> ID de nodo.
            - node_id_to_index: mapeo ID -> índice.
            - link_types: lista de tipos de enlace.
            - in_edges_idx_tonode, out_edges_idx_tonode: listas con índices de aristas entrantes/salientes por nodo.
    Raises:
        FileNotFoundError: Si no se encuentra el archivo pickle.
    """


x = 
[
    is zat, is_virtual_zat, is_intersection, is_virtual_intersection, gen, attr
]

edge_index = 
[
    [i1, i2,...],
    [j1, j2,...]
]

observed_flow = 
[
    1, 2, 10, 40,...
]

node_coordinates =
[
    (xi, yi) or [[x1, x2],[y1, y2]]
]

node_types = {
    is zat: [1, 3,...],
    is_virtual_zat: [2, 4,...],
    is_intersection: [6, 10,...],
    is_virtual_intersection: [5, 7, 8,...]}

zat_demands = [(1, 20, 50), (2, 50, 20)]

link_types = {
    is_logic: [1, 3,...],
    is_virtual: [2, 4,...],
    is_road: [6, 10,...]}

In [7]:
import pickle
# Cargar el archivo pickle
with open("traffic_data_2.pkl", "rb") as file:
    data = pickle.load(file)

In [8]:
# Imprimir las claves del diccionario
data.keys()

dict_keys(['config', 'nodes_features', 'links_topology', 'od_matrix', 'observed_flows', 'results_df', 'node_ids', 'link_ids'])

Columnas: dict_keys(['config', 'nodes_features', 'links_topology', 'od_matrix', 'observed_flows', 'results_df', 'node_ids', 'link_ids'])

In [9]:
# Imprimir el tipo de cada columna
for key in data.keys():
    print(f"Formato de '{key}': {type(data[key])}")

Formato de 'config': <class 'dict'>
Formato de 'nodes_features': <class 'numpy.ndarray'>
Formato de 'links_topology': <class 'numpy.ndarray'>
Formato de 'od_matrix': <class 'numpy.ndarray'>
Formato de 'observed_flows': <class 'numpy.ndarray'>
Formato de 'results_df': <class 'pandas.core.frame.DataFrame'>
Formato de 'node_ids': <class 'numpy.ndarray'>
Formato de 'link_ids': <class 'numpy.ndarray'>


In [10]:
# Mostrar una muestra pequeña de cada variable
for key in data.keys():
    print(f"Muestra de '{key}':", data[key][:5] if isinstance(data[key], list) else data[key])

Muestra de 'config': {'num_nodes': 5, 'demand_range': (1, 10), 'completeness': 50, 'coverage': 30, 'flow_range': (1, 50), 'seed_network': 123, 'seed_observed': 456}
Muestra de 'nodes_features': [[15  7]
 [23 16]
 [14 22]
 [20 26]
 [ 9 10]]
Muestra de 'links_topology': [[0 2]
 [2 0]
 [0 3]
 [3 1]
 [4 2]
 [4 3]
 [4 0]
 [0 1]
 [1 3]
 [3 4]]
Muestra de 'od_matrix': [[ 0  1  3]
 [ 0  2  3]
 [ 0  3  7]
 [ 0  4  2]
 [ 1  0  4]
 [ 1  2 10]
 [ 1  3  7]
 [ 1  4  2]
 [ 2  0  1]
 [ 2  1  2]
 [ 2  3 10]
 [ 2  4  1]
 [ 3  0  1]
 [ 3  1 10]
 [ 3  2  4]
 [ 3  4  5]
 [ 4  0  1]
 [ 4  1  1]
 [ 4  2  5]
 [ 4  3  2]]
Muestra de 'observed_flows': [[ 0  1 25]
 [ 3  4 42]
 [ 4  0  3]]
Muestra de 'results_df':    origin  dest  estimated_flow  observed_flow
0       0     2             3.0            NaN
1       2     0            17.0            NaN
2       0     3             0.0            NaN
3       3     1            11.0            NaN
4       4     2            22.0            NaN
5       4     3       

Muestra de 'nodes_features': [[15  7]
 [23 16]
 [14 22]
 [20 26]
 [ 9 10]]

nodes_features: salidas, entradas

Muestra de 'links_topology': [[0 2]
 [2 0]
 [0 3]
 [3 1]
 [4 2]
 [4 3]
 [4 0]
 [0 1]
 [1 3]
 [3 4]]

 links_topology: INODE JNODE


Muestra de 'od_matrix': [[ 0  1  3]
 [ 0  2  3]
 [ 0  3  7]
 [ 0  4  2]
 [ 1  0  4]
 [ 1  2 10]
 [ 1  3  7]
 [ 1  4  2]
 [ 2  0  1]
 [ 2  1  2]
 [ 2  3 10]
 [ 2  4  1]
 [ 3  0  1]
 [ 3  1 10]
 [ 3  2  4]
 [ 3  4  5]
 [ 4  0  1]
 [ 4  1  1]
 [ 4  2  5]
 [ 4  3  2]]

 ODM = origin_zone, destination, people (NAME get ID) OVER THE TIME


Muestra de 'observed_flows': [[ 0  1 25]
 [ 3  4 42]
 [ 4  0  3]]

 INODE, JNODE, get Adt_axel_par == 'Stickprovsmätning', OVER THE YEARS

Muestra de 'results_df':    origin  dest  estimated_flow  observed_flow
0       0     2             3.0            NaN
1       2     0            17.0            NaN
2       0     3             0.0            NaN
3       3     1            11.0            NaN
4       4     2            22.0            NaN
5       4     3            16.0            NaN
6       4     0             3.0            3.0
7       0     1            25.0           25.0
8       1     3            43.0            NaN
9       3     4            42.0           42.0

???

Muestra de 'node_ids': [0 1 2 3 4]


nodes_ids = nodos['ID']

Muestra de 'link_ids': [[0 2]
 [2 0]
 [0 3]
 [3 1]
 [4 2]
 [4 3]
 [4 0]
 [0 1]
 [1 3]
 [3 4]]

 LINKS INODE, JNODE