In [2]:
import pandas as pd

odm = pd.read_csv("C:/Users/SEJC94056/Documents/AADT_CodeProject/GAT-Applied/layer_procesing/data/Mobile Data/odm.csv", encoding='utf-8', sep=';')

In [5]:
odm['people'].sum()/29

np.float64(308675.0)

# Lastkajen
# Telia OD csv
# Real Network

"""
    Carga datos de tráfico desde un archivo pickle y construye un objeto Data de PyTorch Geometric.

    El archivo pickle debe contener un diccionario con claves 'nodes' y 'links' que incluyen:
      - nodes: 'node.ids', 'node.type', 'node.coordinates', 'node.demand'
      - links: 'link.ids', 'link.type', 'link.ij', 'link.observed_flow'

    Se buscan el archivo en múltiples rutas si es necesario.

    Args:
        pickle_name (str): Ruta relativa del archivo pickle (p.ej., "data/traffic_data_10.pkl").

    Returns:
        Data: Objeto PyTorch Geometric con atributos:
            - x: tensor de características [num_nodes, 4] (ej. [is_zat, is_intersection, gen, attr]).
            - edge_index: tensor de aristas [2, num_edges].
            - observed_flow_indices, observed_flow_values: tensores para flujos observados.
            - node_coordinates: lista de coordenadas para visualización.
            - node_types: lista de tipos de nodo.
            - zat_demands: diccionario con demandas de nodos ZAT.
            - node_id_map_rev: mapeo índice -> ID de nodo.
            - node_id_to_index: mapeo ID -> índice.
            - link_types: lista de tipos de enlace.
            - in_edges_idx_tonode, out_edges_idx_tonode: listas con índices de aristas entrantes/salientes por nodo.
    Raises:
        FileNotFoundError: Si no se encuentra el archivo pickle.
    """


x = 
[
    is zat, is_virtual_zat, is_intersection, is_virtual_intersection, gen, attr
]

edge_index = 
[
    [i1, i2,...],
    [j1, j2,...]
]

observed_flow = 
[
    1, 2, 10, 40,...
]

node_coordinates =
[
    (xi, yi) or [[x1, x2],[y1, y2]]
]

node_types = {
    is zat: [1, 3,...],
    is_virtual_zat: [2, 4,...],
    is_intersection: [6, 10,...],
    is_virtual_intersection: [5, 7, 8,...]}

zat_demands = [(1, 20, 50), (2, 50, 20)]

link_types = {
    is_logic: [1, 3,...],
    is_virtual: [2, 4,...],
    is_road: [6, 10,...]}

In [7]:
import pickle
# Cargar el archivo pickle
with open("traffic_data_2.pkl", "rb") as file:
    data = pickle.load(file)

In [8]:
# Imprimir las claves del diccionario
data.keys()

dict_keys(['config', 'nodes_features', 'links_topology', 'od_matrix', 'observed_flows', 'results_df', 'node_ids', 'link_ids'])

Columnas: dict_keys(['config', 'nodes_features', 'links_topology', 'od_matrix', 'observed_flows', 'results_df', 'node_ids', 'link_ids'])

In [9]:
# Imprimir el tipo de cada columna
for key in data.keys():
    print(f"Formato de '{key}': {type(data[key])}")

Formato de 'config': <class 'dict'>
Formato de 'nodes_features': <class 'numpy.ndarray'>
Formato de 'links_topology': <class 'numpy.ndarray'>
Formato de 'od_matrix': <class 'numpy.ndarray'>
Formato de 'observed_flows': <class 'numpy.ndarray'>
Formato de 'results_df': <class 'pandas.core.frame.DataFrame'>
Formato de 'node_ids': <class 'numpy.ndarray'>
Formato de 'link_ids': <class 'numpy.ndarray'>


In [10]:
# Mostrar una muestra pequeña de cada variable
for key in data.keys():
    print(f"Muestra de '{key}':", data[key][:5] if isinstance(data[key], list) else data[key])

Muestra de 'config': {'num_nodes': 5, 'demand_range': (1, 10), 'completeness': 50, 'coverage': 30, 'flow_range': (1, 50), 'seed_network': 123, 'seed_observed': 456}
Muestra de 'nodes_features': [[15  7]
 [23 16]
 [14 22]
 [20 26]
 [ 9 10]]
Muestra de 'links_topology': [[0 2]
 [2 0]
 [0 3]
 [3 1]
 [4 2]
 [4 3]
 [4 0]
 [0 1]
 [1 3]
 [3 4]]
Muestra de 'od_matrix': [[ 0  1  3]
 [ 0  2  3]
 [ 0  3  7]
 [ 0  4  2]
 [ 1  0  4]
 [ 1  2 10]
 [ 1  3  7]
 [ 1  4  2]
 [ 2  0  1]
 [ 2  1  2]
 [ 2  3 10]
 [ 2  4  1]
 [ 3  0  1]
 [ 3  1 10]
 [ 3  2  4]
 [ 3  4  5]
 [ 4  0  1]
 [ 4  1  1]
 [ 4  2  5]
 [ 4  3  2]]
Muestra de 'observed_flows': [[ 0  1 25]
 [ 3  4 42]
 [ 4  0  3]]
Muestra de 'results_df':    origin  dest  estimated_flow  observed_flow
0       0     2             3.0            NaN
1       2     0            17.0            NaN
2       0     3             0.0            NaN
3       3     1            11.0            NaN
4       4     2            22.0            NaN
5       4     3       

Muestra de 'nodes_features': [[15  7]
 [23 16]
 [14 22]
 [20 26]
 [ 9 10]]

nodes_features: salidas, entradas

Muestra de 'links_topology': [[0 2]
 [2 0]
 [0 3]
 [3 1]
 [4 2]
 [4 3]
 [4 0]
 [0 1]
 [1 3]
 [3 4]]

 links_topology: INODE JNODE


Muestra de 'od_matrix': [[ 0  1  3]
 [ 0  2  3]
 [ 0  3  7]
 [ 0  4  2]
 [ 1  0  4]
 [ 1  2 10]
 [ 1  3  7]
 [ 1  4  2]
 [ 2  0  1]
 [ 2  1  2]
 [ 2  3 10]
 [ 2  4  1]
 [ 3  0  1]
 [ 3  1 10]
 [ 3  2  4]
 [ 3  4  5]
 [ 4  0  1]
 [ 4  1  1]
 [ 4  2  5]
 [ 4  3  2]]

 ODM = origin_zone, destination, people (NAME get ID) OVER THE TIME


Muestra de 'observed_flows': [[ 0  1 25]
 [ 3  4 42]
 [ 4  0  3]]

 INODE, JNODE, get Adt_axel_par == 'Stickprovsmätning', OVER THE YEARS

Muestra de 'results_df':    origin  dest  estimated_flow  observed_flow
0       0     2             3.0            NaN
1       2     0            17.0            NaN
2       0     3             0.0            NaN
3       3     1            11.0            NaN
4       4     2            22.0            NaN
5       4     3            16.0            NaN
6       4     0             3.0            3.0
7       0     1            25.0           25.0
8       1     3            43.0            NaN
9       3     4            42.0           42.0

???

Muestra de 'node_ids': [0 1 2 3 4]


nodes_ids = nodos['ID']

Muestra de 'link_ids': [[0 2]
 [2 0]
 [0 3]
 [3 1]
 [4 2]
 [4 3]
 [4 0]
 [0 1]
 [1 3]
 [3 4]]

 LINKS INODE, JNODE

In [42]:
import pandas as pd
from dataclasses import dataclass, field
import warnings

In [79]:
@dataclass
class VDFPreprocessor:
    """
    Preprocesador para generar grupos de curvas VDF y asignar parámetros alpha/beta y capacidad.
    """
    df: pd.DataFrame
    road_df: pd.DataFrame = field(init=False)
    nonroad_df: pd.DataFrame = field(init=False)
    vdf_groups: dict = field(init=False, default_factory=dict)
    params: dict = field(init=False, default_factory=dict)
    capacities: dict = field(init=False, default_factory=dict)
    last_group_by: str = field(init=False, default=None)

    def __post_init__(self):
        self.df = self.df.copy()
        self.split_by_edge_type()
        self.extract_columns()

    def split_by_edge_type(self):
        mask = self.df['edge_type'] == 'road'
        self.road_df = self.df[mask].copy()
        self.nonroad_df = self.df[~mask].copy()

    def extract_columns(self):
        cols = ['emme_LANES', 'emme_VDF', 'emme_@hast', 'LENGTH', 'emme_@vtyp']
        self.road_df = self.road_df[cols]

    def group_curves(self, by: str):
        """
        Agrupa por 'emme_@vtyp', 'emme_VDF' o 'composite'.
        - emme_VDF: VDF__{emme_VDF}_TYP{emme_@vtyp}_SP_{emme_@hast}_LNS_{emme_LANES}
        - emme_@vtyp: TYP{emme_@vtyp}_SP_{emme_@hast}_LNS_{emme_LANES}
        - composite: COMP__TYP{emme_@vtyp}_SP_{emme_@hast}
        Verifica consistencia de atributos en cada grupo; lanza warning si no.
        """
        valid = ('emme_@vtyp', 'emme_VDF', 'composite')
        if by not in valid:
            raise ValueError(f"by debe ser uno de {valid}")
        self.vdf_groups.clear()
        self.params.clear()
        self.capacities.clear()
        self.last_group_by = by

        if by == 'composite':
            keys = self.road_df[['emme_@vtyp','emme_@hast']].drop_duplicates()
            for _, row in keys.iterrows():
                vtyp, hast = row['emme_@vtyp'], row['emme_@hast']
                subdf = self.road_df[(self.road_df['emme_@vtyp']==vtyp) & (self.road_df['emme_@hast']==hast)]
                name = f"COMP_TYP{vtyp}_SP_{hast}"
                self._add_group(name, subdf)
        else:
            for key, subdf in self.road_df.groupby(by):
                self._add_group_by_key(by, key, subdf)

        # inicializar alpha/beta y capacidad a pd.NA
        for name in self.vdf_groups:
            self.params[name] = {'alpha': pd.NA, 'beta': pd.NA}
            self.capacities[name] = pd.NA

    def _add_group_by_key(self, by, key, subdf):
        unique = {
            'vtyp': subdf['emme_@vtyp'].unique(),
            'vdf':  subdf['emme_VDF'].unique(),
            'hast': subdf['emme_@hast'].unique(),
            'lanes': subdf['emme_LANES'].unique()
        }
        for attr, vals in unique.items():
            if len(vals) > 1:
                warnings.warn(f"Inconsistencia en grupo '{key}': {attr} tiene valores {vals}")
        vtyp = unique['vtyp'][0]
        vdf  = unique['vdf'][0]
        hast = unique['hast'][0]
        lanes= unique['lanes'][0]
        if by == 'emme_VDF':
            name = f"VDF_{vdf}_TYP{vtyp}_SP_{hast}_LNS_{lanes}"
        else:
            name = f"TYP{vtyp}_SP_{hast}_LNS_{lanes}"
        self._add_group(name, subdf)

    def _add_group(self, name, subdf):
        self.vdf_groups[name] = subdf.copy()

    def set_manual_params(self, manual_params: dict):
        for name, p in manual_params.items():
            if name not in self.vdf_groups:
                raise KeyError(f"No existe el grupo VDF '{name}'")
            self.params[name]['alpha'] = p.get('alpha', pd.NA)
            self.params[name]['beta']  = p.get('beta', pd.NA)

    def set_capacity(self, cap_params: dict):
        """Asigna capacidad (cap) a cada vdf_name similar a set_manual_params."""
        for name, cap in cap_params.items():
            if name not in self.vdf_groups:
                raise KeyError(f"No existe el grupo VDF '{name}'")
            self.capacities[name] = cap

    def preview(self) -> pd.DataFrame:
        """
        Devuelve DataFrame con columnas:
        [vdf_name, capacidad, ff_tt, emme_LANES, alpha, beta]
        """
        rows = []
        for name, subdf in self.vdf_groups.items():
            sample = subdf.iloc[0]
            rows.append({
                'vdf_name': name,
                'capacity': self.capacities.get(name),
                'FFS': sample['emme_@hast'],
                'lanes': sample['emme_LANES'],
                'alpha': self.params[name]['alpha'],
                'beta': self.params[name]['beta'],
            })
        return pd.DataFrame(rows)

    def get_compact_output(self) -> (pd.DataFrame, list):
        """
        Retorna:
        - DataFrame [vdf_name, capacidad, ff_tt, emme_LANES, alpha, beta]
        - Lista de índices que mapean cada fila de road_df a su vdf_name
        """
        df_params = self.preview()
        # mapa original index -> grupo
        idx_map = []
        for idx, row in self.road_df.iterrows():
            for name, subdf in self.vdf_groups.items():
                if idx in subdf.index:
                    idx_map.append((idx, name))
                    break
        return df_params, idx_map

In [48]:
# 1. Preparamos el DataFrame original
df = pd.read_csv("C:/Users/SEJC94056/Documents/AADT_CodeProject/GAT-Applied/layer_procesing/data/geopackages/Final_Links_DataFrame.csv", sep=";", encoding="utf-8")

In [45]:
df.columns

Index(['fid', 'INODE', 'JNODE', 'LENGTH', 'emme_LANES', 'emme_VDF',
       'emme_@hast', 'emme_@vkat', 'emme_@vnr', 'emme_@vtyp',
       ...
       'DIRECTION', 'ROLE', 'SEQ_NO', 'Avsnittsidentitet', 'year', 'Strategy',
       'blend_id', 'temporal_sources', 'match_score', 'edge_type'],
      dtype='object', length=150)

In [80]:
# 2. Creamos el preprocesador
vp = VDFPreprocessor(df)

# 3. Elegimos la forma de agrupar: por emme_@vtyp o por emme_VDF
vp.group_curves(by='emme_VDF')
# —> agrupa en vp.vdf_groups y deja alpha/beta en pd.NA

# 4. (Opcional) Vemos una tabla previa:
vp.preview()

vdf_name capacity    FFS  lanes alpha  beta
0     VDF_1.0_TYP5.0_SP_120.0_LNS_4.0     <NA>  120.0    4.0  <NA>  <NA>
1     VDF_3.0_TYP5.0_SP_110.0_LNS_4.0     <NA>  110.0    4.0  <NA>  <NA>
2      VDF_7.0_TYP5.0_SP_90.0_LNS_4.0     <NA>   90.0    4.0  <NA>  <NA>
3     VDF_11.0_TYP5.0_SP_70.0_LNS_4.0     <NA>   70.0    4.0  <NA>  <NA>
4     VDF_16.0_TYP4.0_SP_80.0_LNS_4.0     <NA>   80.0    4.0  <NA>  <NA>
5     VDF_18.0_TYP4.0_SP_70.0_LNS_4.0     <NA>   70.0    4.0  <NA>  <NA>
6     VDF_19.0_TYP4.0_SP_70.0_LNS_4.0     <NA>   70.0    4.0  <NA>  <NA>
7     VDF_20.0_TYP4.0_SP_70.0_LNS_4.0     <NA>   70.0    4.0  <NA>  <NA>
8     VDF_23.0_TYP4.0_SP_60.0_LNS_4.0     <NA>   60.0    4.0  <NA>  <NA>
9     VDF_24.0_TYP4.0_SP_60.0_LNS_4.0     <NA>   60.0    4.0  <NA>  <NA>
10    VDF_27.0_TYP4.0_SP_50.0_LNS_4.0     <NA>   50.0    4.0  <NA>  <NA>
11    VDF_28.0_TYP4.0_SP_50.0_LNS_4.0     <NA>   50.0    4.0  <NA>  <NA>
12    VDF_29.0_TYP4.0_SP_50.0_LNS_4.0     <NA>   50.0    4.0  <NA>  <NA>
13    VDF_30.0_TYP4.0_SP_40.0_LNS_4.0     <NA>   40.0    4.0  <NA>  <NA>
14    VDF_31.0_TYP4.0_SP_40.0_LNS_4.0     <NA>   40.0    4.0  <NA>  <NA>
15    VDF_32.0_TYP4.0_SP_40.0_LNS_4.0     <NA>   40.0    4.0  <NA>  <NA>
16  VDF_41.0_TYP10.0_SP_110.0_LNS_3.0     <NA>  110.0    3.0  <NA>  <NA>
17  VDF_43.0_TYP10.0_SP_100.0_LNS_3.0     <NA>  100.0    3.0  <NA>  <NA>
18   VDF_46.0_TYP10.0_SP_80.0_LNS_3.0     <NA>   80.0    3.0  <NA>  <NA>
19   VDF_47.0_TYP10.0_SP_70.0_LNS_3.0     <NA>   70.0    3.0  <NA>  <NA>
20   VDF_51.0_TYP9.0_SP_100.0_LNS_2.0     <NA>  100.0    2.0  <NA>  <NA>
21    VDF_53.0_TYP9.0_SP_90.0_LNS_2.0     <NA>   90.0    2.0  <NA>  <NA>
22    VDF_54.0_TYP9.0_SP_90.0_LNS_2.0     <NA>   90.0    2.0  <NA>  <NA>
23    VDF_55.0_TYP9.0_SP_90.0_LNS_2.0     <NA>   90.0    2.0  <NA>  <NA>
24    VDF_56.0_TYP9.0_SP_90.0_LNS_2.0     <NA>   90.0    2.0  <NA>  <NA>
25    VDF_57.0_TYP9.0_SP_80.0_LNS_2.0     <NA>   80.0    2.0  <NA>  <NA>
26    VDF_58.0_TYP9.0_SP_80.0_LNS_2.0     <NA>   80.0    2.0  <NA>  <NA>
27    VDF_59.0_TYP9.0_SP_80.0_LNS_2.0     <NA>   80.0    2.0  <NA>  <NA>
28    VDF_60.0_TYP9.0_SP_80.0_LNS_2.0     <NA>   80.0    2.0  <NA>  <NA>
29    VDF_61.0_TYP9.0_SP_70.0_LNS_2.0     <NA>   70.0    2.0  <NA>  <NA>
30    VDF_62.0_TYP9.0_SP_70.0_LNS_2.0     <NA>   70.0    2.0  <NA>  <NA>
31    VDF_63.0_TYP9.0_SP_70.0_LNS_2.0     <NA>   70.0    2.0  <NA>  <NA>
32    VDF_64.0_TYP9.0_SP_70.0_LNS_2.0     <NA>   70.0    2.0  <NA>  <NA>
33    VDF_65.0_TYP9.0_SP_70.0_LNS_2.0     <NA>   70.0    2.0  <NA>  <NA>
34    VDF_66.0_TYP9.0_SP_70.0_LNS_2.0     <NA>   70.0    2.0  <NA>  <NA>
35    VDF_67.0_TYP9.0_SP_70.0_LNS_2.0     <NA>   70.0    2.0  <NA>  <NA>
36    VDF_68.0_TYP9.0_SP_60.0_LNS_2.0     <NA>   60.0    2.0  <NA>  <NA>
37    VDF_69.0_TYP9.0_SP_60.0_LNS_2.0     <NA>   60.0    2.0  <NA>  <NA>
38    VDF_70.0_TYP9.0_SP_60.0_LNS_2.0     <NA>   60.0    2.0  <NA>  <NA>
39    VDF_71.0_TYP9.0_SP_50.0_LNS_2.0     <NA>   50.0    2.0  <NA>  <NA>
40    VDF_72.0_TYP9.0_SP_50.0_LNS_2.0     <NA>   50.0    2.0  <NA>  <NA>
41    VDF_73.0_TYP9.0_SP_50.0_LNS_2.0     <NA>   50.0    2.0  <NA>  <NA>
42    VDF_74.0_TYP9.0_SP_40.0_LNS_2.0     <NA>   40.0    2.0  <NA>  <NA>
43    VDF_75.0_TYP9.0_SP_40.0_LNS_2.0     <NA>   40.0    2.0  <NA>  <NA>
44    VDF_76.0_TYP9.0_SP_40.0_LNS_2.0     <NA>   40.0    2.0  <NA>  <NA>

In [39]:
vp.group_curves(by='emme_@vtyp')
# —> agrupa en vp.vdf_groups y deja alpha/beta en pd.NA

# 4. (Opcional) Vemos una tabla previa:
print(vp.preview())

                  vdf_name  emme_LANES     tt_ff alpha  beta
0   TYP4.0_SP_60.0_LNS_4.0         4.0  0.000028  <NA>  <NA>
1  TYP5.0_SP_120.0_LNS_4.0         4.0  0.001342  <NA>  <NA>
2   TYP9.0_SP_40.0_LNS_2.0         2.0  0.000097  <NA>  <NA>
3  TYP10.0_SP_70.0_LNS_3.0         3.0  0.000043  <NA>  <NA>


C:\Users\SEJC94056\AppData\Local\Temp\ipykernel_16540\267195263.py:58: UserWarning: Inconsistencia en grupo '4.0': vdf tiene valores [24. 20. 30. 27. 19. 28. 16. 31. 23. 32. 18. 29.]
  warnings.warn(
C:\Users\SEJC94056\AppData\Local\Temp\ipykernel_16540\267195263.py:58: UserWarning: Inconsistencia en grupo '4.0': hast tiene valores [60. 70. 40. 50. 80.]
  warnings.warn(
C:\Users\SEJC94056\AppData\Local\Temp\ipykernel_16540\267195263.py:58: UserWarning: Inconsistencia en grupo '5.0': vdf tiene valores [ 1.  7. 11.  3.]
  warnings.warn(
C:\Users\SEJC94056\AppData\Local\Temp\ipykernel_16540\267195263.py:58: UserWarning: Inconsistencia en grupo '5.0': hast tiene valores [120.  90.  70. 110.]
  warnings.warn(
C:\Users\SEJC94056\AppData\Local\Temp\ipykernel_16540\267195263.py:58: UserWarning: Inconsistencia en grupo '9.0': vdf tiene valores [75. 71. 64. 69. 72. 76. 62. 61. 68. 51. 66. 73. 67. 74. 63. 60. 59. 54.
 55. 56. 57. 65. 58. 53. 70.]
  warnings.warn(
C:\Users\SEJC94056\AppData\Local\

In [ ]:
# 5. Definimos manualmente algunos parámetros:
manual = {
    'VDF_4.0':            {'alpha': 0.15, 'beta': 4},
    'VDF_5.0':            {'alpha': 0.15, 'beta': 4},
    'VDF_9.0':            {'alpha': 0.15, 'beta': 4},
    'VDF_10.0':           {'alpha': 0.15, 'beta': 4},
    # si hay más curvas, pueden omitirse: se quedan en pd.NA
}
vp.set_manual_params(manual)

In [60]:
capacity = {
    'VDF_4.0':            2000,
    'VDF_5.0':            2000,
    'VDF_9.0':            2000,
    'VDF_10.0':           2000,
}
vp.set_capacity(capacity)

KeyError: "No existe el grupo VDF 'VDF_4.0'"

In [40]:
# 6. Volvemos a ver la tabla con los alphas/betas actualizados
print(vp.preview())

                  vdf_name  emme_LANES     tt_ff alpha  beta
0   TYP4.0_SP_60.0_LNS_4.0         4.0  0.000028  <NA>  <NA>
1  TYP5.0_SP_120.0_LNS_4.0         4.0  0.001342  <NA>  <NA>
2   TYP9.0_SP_40.0_LNS_2.0         2.0  0.000097  <NA>  <NA>
3  TYP10.0_SP_70.0_LNS_3.0         3.0  0.000043  <NA>  <NA>


In [41]:
# 7. Obtenemos el DataFrame “compacto” para la función BPR
compacto = vp.get_compact_output()
compacto
# compacto tendrá columnas ['vdf_name', 'alpha', 'beta']

vdf_name alpha  beta
0   TYP4.0_SP_60.0_LNS_4.0  <NA>  <NA>
1  TYP5.0_SP_120.0_LNS_4.0  <NA>  <NA>
2   TYP9.0_SP_40.0_LNS_2.0  <NA>  <NA>
3  TYP10.0_SP_70.0_LNS_3.0  <NA>  <NA>

In [7]:
import pandas as pd
from dataclasses import dataclass, field
import warnings

@dataclass
class VDFPreprocessor:
    """
    Preprocesador para generar grupos de curvas VDF y asignar parámetros alpha/beta y capacidad.
    """
    df: pd.DataFrame
    default_alpha: float = 0.15
    default_beta: float = 4.0
    default_capacity: float = 2000.0

    road_df: pd.DataFrame = field(init=False)
    nonroad_df: pd.DataFrame = field(init=False)
    vdf_groups: dict = field(init=False, default_factory=dict)
    params: dict = field(init=False, default_factory=dict)
    capacities: dict = field(init=False, default_factory=dict)
    last_group_by: str = field(init=False, default=None)

    def __post_init__(self):
        self.df = self.df.copy()
        self.split_by_edge_type()
        self.extract_columns()

    def split_by_edge_type(self):
        mask = self.df['edge_type'] == 'road'
        self.road_df = self.df[mask].copy()
        self.nonroad_df = self.df[~mask].copy()

    def extract_columns(self):
        cols = ['emme_LANES', 'emme_VDF', 'emme_@hast', 'LENGTH', 'emme_@vtyp']
        self.road_df = self.road_df[cols]


    def group_curves(self, by: str):
        """
        Agrupa por:
          - 'emme_VDF': curvas con nombre 'VDF_{emme_VDF}'
          - 'emme_@vtyp': curvas con nombre 'VTYP_{emme_@vtyp}'
          - 'composite': curvas con nombre 'VDF_{emme_VDF}_VTYP_{emme_@vtyp}'
        Verifica consistencia; inicializa parámetros por defecto.
        """
        valid = ('emme_VDF', 'emme_@vtyp', 'composite')
        if by not in valid:
            raise ValueError(f"by debe ser uno de {valid}")

        self.vdf_groups.clear()
        self.params.clear()
        self.capacities.clear()
        self.last_group_by = by

        if by == 'composite':
            # agrupación por combinación VDF + vtyp
            keys = self.road_df.dropna(subset=['emme_@vtyp', 'emme_@hast'])[['emme_@vtyp', 'emme_@hast']].drop_duplicates()
            for _, row in keys.iterrows():
                speed_val, vtyp_val = row['emme_@hast'], row['emme_@vtyp']
                subdf = self.road_df[
                    (self.road_df['emme_@hast'] == speed_val) &
                    (self.road_df['emme_@vtyp'] == vtyp_val)
                ]
                # verificar consistencia de valores clave
                for col in ('emme_@hast', 'emme_@vtyp'):
                    vals = subdf[col].unique()
                    if len(vals) > 1:
                        warnings.warn(
                            f"Inconsistencia en composite grupo {col}: {vals}")
                name = f"VTYP_{vtyp_val}_SP_{speed_val}"
                self.vdf_groups[name] = subdf.copy()
        elif by == 'emme_VDF':
            for vdf_val, subdf in self.road_df.groupby('emme_VDF'):
                if subdf['emme_VDF'].nunique() > 1:
                    warnings.warn(f"Inconsistencia en grupo emme_VDF {vdf_val}")
                name = f"VDF_{vdf_val}"
                self.vdf_groups[name] = subdf.copy()
        else:  # by == 'emme_@vtyp'
            for vtyp_val, subdf in self.road_df.groupby('emme_@vtyp'):
                if subdf['emme_@vtyp'].nunique() > 1:
                    warnings.warn(f"Inconsistencia en grupo emme_@vtyp {vtyp_val}")
                name = f"VTYP_{vtyp_val}"
                self.vdf_groups[name] = subdf.copy()

        # inicializar con valores por defecto
        for name in self.vdf_groups:
            self.params[name] = {'alpha': self.default_alpha, 'beta': self.default_beta}
            self.capacities[name] = self.default_capacity

    def set_manual_params(self, manual_params: dict):
        for name, p in manual_params.items():
            if name not in self.params:
                raise KeyError(f"No existe el grupo VDF '{name}'")
            self.params[name]['alpha'] = p.get('alpha', self.params[name]['alpha'])
            self.params[name]['beta']  = p.get('beta',  self.params[name]['beta'])

    def set_capacity(self, cap_params: dict):
        for name, cap in cap_params.items():
            if name not in self.capacities:
                raise KeyError(f"No existe el grupo VDF '{name}'")
            self.capacities[name] = cap

    def preview(self) -> pd.DataFrame:
        rows = []
        for name, subdf in self.vdf_groups.items():
            sample = subdf.iloc[0]
            rows.append({
                'vdf_name': name,
                'capacity': self.capacities[name],
                'ff_speed': sample['emme_@hast'],
                'lanes': sample['emme_LANES'],
                'alpha': self.params[name]['alpha'],
                'beta': self.params[name]['beta'],
            })
        return pd.DataFrame(rows)

    def get_compact_output(self) -> (pd.DataFrame, list):
        df_params = self.preview()
        idx_map = []
        for idx in self.road_df.index:
            for name, subdf in self.vdf_groups.items():
                if idx in subdf.index:
                    idx_map.append(name)
                    break
        return df_params, idx_map

In [8]:
df = pd.read_csv("C:/Users/SEJC94056/Documents/AADT_CodeProject/GAT-Applied/layer_procesing/data/geopackages/Final_Links_DataFrame.csv", sep=";", encoding="utf-8")
vp = VDFPreprocessor(df)
vp.group_curves(by='composite')
# —> agrupa en vp.vdf_groups y deja alpha/beta en pd.NA
# 4. (Opcional) Vemos una tabla previa:
vp.preview()

vdf_name  capacity  ff_speed  lanes  alpha  beta
0     VTYP_9.0_SP_40.0    2000.0      40.0    2.0   0.15   4.0
1     VTYP_9.0_SP_50.0    2000.0      50.0    2.0   0.15   4.0
2     VTYP_9.0_SP_70.0    2000.0      70.0    2.0   0.15   4.0
3     VTYP_9.0_SP_60.0    2000.0      60.0    2.0   0.15   4.0
4    VTYP_10.0_SP_70.0    2000.0      70.0    3.0   0.15   4.0
5     VTYP_4.0_SP_60.0    2000.0      60.0    4.0   0.15   4.0
6    VTYP_10.0_SP_80.0    2000.0      80.0    3.0   0.15   4.0
7    VTYP_9.0_SP_100.0    2000.0     100.0    2.0   0.15   4.0
8   VTYP_10.0_SP_100.0    2000.0     100.0    3.0   0.15   4.0
9     VTYP_4.0_SP_70.0    2000.0      70.0    4.0   0.15   4.0
10    VTYP_4.0_SP_40.0    2000.0      40.0    4.0   0.15   4.0
11    VTYP_9.0_SP_80.0    2000.0      80.0    2.0   0.15   4.0
12    VTYP_9.0_SP_90.0    2000.0      90.0    2.0   0.15   4.0
13    VTYP_4.0_SP_50.0    2000.0      50.0    4.0   0.15   4.0
14   VTYP_5.0_SP_120.0    2000.0     120.0    4.0   0.15   4.0
15    VTYP_4.0_SP_80.0    2000.0      80.0    4.0   0.15   4.0
16    VTYP_5.0_SP_90.0    2000.0      90.0    4.0   0.15   4.0
17    VTYP_5.0_SP_70.0    2000.0      70.0    4.0   0.15   4.0
18   VTYP_5.0_SP_110.0    2000.0     110.0    4.0   0.15   4.0
19  VTYP_10.0_SP_110.0    2000.0     110.0    3.0   0.15   4.0

In [97]:
params, indices = vp.get_compact_output()

In [98]:
params

vdf_name  capacity  ff_speed  lanes  alpha  beta
0   VTYP_4.0    2000.0      60.0    4.0   0.15   4.0
1   VTYP_5.0    2000.0     120.0    4.0   0.15   4.0
2   VTYP_9.0    2000.0      40.0    2.0   0.15   4.0
3  VTYP_10.0    2000.0      70.0    3.0   0.15   4.0

vdf_name;capacity;ff_speed;lanes;alpha;beta
VTYP_4.0;2000.0;60.0;4.0;0.15;4.0
VTYP_5.0;2000.0;120.0;4.0;0.15;4.0
VTYP_9.0;2000.0;40.0;2.0;0.15;4.0
VTYP_10.0;2000.0;70.0;3.0;0.15;4.0

In [ ]:
['VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 ...]

In [99]:
indices

['VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_10.0',
 'VTYP_10.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_4.0',
 'VTYP_9.0',
 'VTYP_10.0',
 'VTYP_10.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_10.0',
 'VTYP_10.0',
 'VTYP_10.0',
 'VTYP_4.0',
 'VTYP_4.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTYP_9.0',
 'VTY

In [112]:
df = pd.read_csv("C:/Users/SEJC94056/Documents/AADT_CodeProject/GAT-Applied/layer_procesing/data/geopackages/Final_Links_DataFrame.csv", sep=";", encoding="utf-8")
df = df[df['edge_type'] == 'road']
df

fid   INODE   JNODE    LENGTH  emme_LANES  emme_VDF  emme_@hast  \
0        1   75001   75002  0.232550         2.0      75.0        40.0   
1        2   75001  147771  0.088640         2.0      75.0        40.0   
2        3   75001  147940  0.390320         2.0      75.0        40.0   
3        4   75002  148092  0.822580         2.0      75.0        40.0   
4        5   75096  147842  0.447720         2.0      71.0        50.0   
...    ...     ...     ...       ...         ...       ...         ...   
1494  1495    1066  146370  0.041126         NaN       NaN         NaN   
1496  1497  146316    1067  0.307350         NaN       NaN         NaN   
1497  1498    1067  146367  0.152891         NaN       NaN         NaN   
1499  1500  148759    1068  0.102375         NaN       NaN         NaN   
1500  1501    1068  148851  0.382326         NaN       NaN         NaN   

      emme_@vkat  emme_@vnr  emme_@vtyp  ...  DIRECTION         ROLE  SEQ_NO  \
0            4.0        0.0         9.0  ...        Med  Syskon fram     0.0   
1            4.0        0.0         9.0  ...        Med       Normal     0.0   
2            4.0       35.0         9.0  ...        Med       Normal     0.0   
3            4.0        0.0         9.0  ...        Med       Normal     0.0   
4            4.0     1027.0         9.0  ...        Med       Normal     0.0   
...          ...        ...         ...  ...        ...          ...     ...   
1494         NaN        NaN         NaN  ...        NaN          NaN     NaN   
1496         NaN        NaN         NaN  ...        NaN          NaN     NaN   
1497         NaN        NaN         NaN  ...        NaN          NaN     NaN   
1499         NaN        NaN         NaN  ...        NaN          NaN     NaN   
1500         NaN        NaN         NaN  ...        NaN          NaN     NaN   

      Avsnittsidentitet    year  Strategy  \
0             8540120.0  2014.0  distance   
1             8540307.0  2014.0     exact   
2             8540117.0  2000.0     exact   
3             8540089.0  2000.0     exact   
4             8540177.0  2000.0     exact   
...                 ...     ...       ...   
1494                NaN     NaN       NaN   
1496                NaN     NaN       NaN   
1497                NaN     NaN       NaN   
1499                NaN     NaN       NaN   
1500                NaN     NaN       NaN   

                                  blend_id  \
0     071881cc-9c63-4547-9972-96924d20f032   
1     6120db58-01a2-426e-a730-809a90173288   
2     32ca63dc-87a1-40a9-ba14-5dc5eb39a384   
3     05fc1a05-32f3-4948-a27b-d5212a9f01b3   
4     c158cc26-a8bd-4a39-9de9-c0d2738f48d5   
...                                    ...   
1494                                   NaN   
1496                                   NaN   
1497                                   NaN   
1499                                   NaN   
1500                                   NaN   

                                       temporal_sources  match_score  \
0     [2014, 2015, 2016, 2017, 2018, 2019, 2020, 202...     0.000000   
1     [2014, 2015, 2016, 2017, 2018, 2019, 2020, 202...     0.500000   
2     [2000, 2001, 2002, 2003, 2004, 2005, 2006, 200...     0.500000   
3            [2000, 2001, 2002, 2003, 2004, 2005, 2006]     0.000000   
4     [2000, 2001, 2002, 2003, 2004, 2005, 2006, 200...     0.931812   
...                                                 ...          ...   
1494                                                NaN          NaN   
1496                                                NaN          NaN   
1497                                                NaN          NaN   
1499                                                NaN          NaN   
1500                                                NaN          NaN   

      edge_type  
0          road  
1          road  
2          road  
3          road  
4          road  
...         ...  
1494       road  
1496       road  
1497       road  
1499       road  


In [122]:
df.dropna(subset=['emme_@vtyp', 'emme_@hast'])[['emme_@vtyp', 'emme_@hast']].drop_duplicates()

emme_@vtyp  emme_@hast
0            9.0        40.0
4            9.0        50.0
5            9.0        70.0
6            9.0        60.0
24          10.0        70.0
38           4.0        60.0
40          10.0        80.0
47           9.0       100.0
48          10.0       100.0
51           4.0        70.0
52           4.0        40.0
240          9.0        80.0
288          9.0        90.0
427          4.0        50.0
503          5.0       120.0
659          4.0        80.0
738          5.0        90.0
742          5.0        70.0
815          5.0       110.0
1060        10.0       110.0